### ISSUE TITLE
How to solve this problem?

### ISSUE THREAD

**Issue by lalalashini** [whywww/ASASM#1]
Traceback (most recent call last):
  File "D:\pycharm\paper\ASASM-publish\ASASM-publish\main.py", line 77, in <module>
    prop2 = LeastSamplingASM(Uin, x, y, z, device)
  File "D:\pycharm\paper\ASASM-publish\ASASM-publish\LSASM.py", line 109, in __init__
    if any(1 - (wavelength * fxmax)**2 - (wavelength * fymax) ** 2 <= 0):
  File "D:\anaconda\envs\pytorchcuda\lib\site-packages\torch\_tensor.py", line 723, in __iter__
    raise TypeError('iteration over a 0-d tensor')
TypeError: iteration over a 0-d tensor

**Comment by whywww** [comment]
Hi, thanks for your comment! I've removed "any" from line 109, LSASM.py as it was left over from the multi-wavelength version... Anyway, it's fixed now:)
